language: node_js
node_js:
- stable
deploy:
  provider: heroku 
  api:
    key:
      secure: CnltEYDajHwJLOYeVq+avDJv+DhfIJaFeRa6vRPg2DWIdttPVFa7aODoJULwjMRAaSpqsJsyGYLlUFB72G9qAjW3F4cmpTNp2iWqlaGUBX16KUMyXUuY9GifD+Ku0eXrBKqI7scDrZygixN0fb78D6pDicZdgNvwzkvJQGZh2iTCaQbIwfUtbAohNZZc+MKcnTJPFV2CQYJaJ2Pk3r8y9lcXoSPswnjx02Ef1vt1IWmkDL2sXKxgZnV7HIFF54O7WdS4g2ROB+3jMBoDAFNFgedMfMv5eoGKQdT4nwVhgLykaF0Davq2JpBVdEbdj6hlSv/LyEh/GVnJDMKsxdh1I3FUhB7OHJKK8n0HgH1a69TT9Di1G5E/4jdh6xmsBt9SK2HhsNA7Ekh9RuJQ1facUe9DwxByzDsnOzSjg/2mq2WALuyTaIuQnfuCAsB1Dpc1UNgqjTJ1IN3v20S7nkwavbSKprQR9NkO5epoh8fR7mLDgIknTIMbD0zxnmQqn/oWyMODxZmcgY5tg0hMbHxt564p6DV/Dz2g7BRenCPFkoPN8CSv2RdKAwc5U108xV+VWZCuxuiG/6Wdd0fzkGuIJg2Nn3OhTC5Xqg2A61pKJ8PwxgsZpvjhyk7YLNCuu7Mk094eW0L9vDZGYch6ZN5A/VNDo4Sp2/MqSU+J/gQWYcc=
